### PR TITLE
Migrated to Bootstrap 4

### LINKED ISSUE #449: Migrating from Bootstrap3 to Bootstrap4
## Description
As a developer,
I need to make sure that the bootstrap version is updated from bootstrap 3 to 4,
so that I can easily make changes in the files following the latest documentation.

## Mocks
N/A

### Update [Required]
- [ ] Bootstrap css and js files need to be updated.
## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
0.5 hours

### PR DESCRIPTION
**Pull request by ritwickraj78**
### Description
Updated the bootstrap version from 3 to 4 so that developers can now work on the latest vesion.

Fixes #449 

### Type of Change:
**Delete irrelevant options.**

- Quality Assurance

**Code/Quality Assurance Only**

- New feature (non-breaking change which adds functionality pre-approved by mentors)

### How Has This Been Tested?
Tested locally on my system. Updating to version 4 breaks nothing.

### Checklist:

- [x] My PR follows the style guidelines of this project
- [x] I have performed a self-review of my own code or materials
- [x] Any dependent changes have been merged 

**Code/Quality Assurance Only**
- [x] My changes generate no new warnings 
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by ritwickraj78** [comment]
@abhi20161997 I have made the necessary changes. Could you please review the changes?

**Comment by abhi20161997** [comment]
@ritwickraj78  LGTM @sammy1997  Please can you have a look too ?

**Comment by sammy1997** [comment]
Still, 2 commits on this. :( Please check it

**Comment by sakshi1499** [comment]
@ritwickraj78 Can you squash and make it to one commit? We can merge then.

**Comment by ritwickraj78** [comment]
@sakshi1499 Sure I'll do the needful

**Comment by ritwickraj78** [comment]
@sakshi1499 @sammy1997  Seems I have pulled from the wrong branch before making the PR. So I am closing this PR and will be opening a new one. Sorry for the inconvenience.

**Comment by sammy1997** [comment]
@ritwickraj78 Yeah go ahead

**Pull request closed without merging**
