### PR TITLE
left and right margins added to pages

### LINKED ISSUE #530: Margins on every page.
## Description
Margins of every page need to be fixed.

## Mocks
reference 
Screenshot-2020-05-09-at-19 00 44

### Update [Required]
- [x] Margins of every page should be fixed.

## Definition of Done
- [ ] All of the required items are completed.
- [x] Approval by 1 mentor.

## Estimation
5 hours

### PR DESCRIPTION
**Pull request by yashshah2820**
### Description
Added 16px margin to right and left of every page as the previous pages were were not having margins.

Fixes #530 

### Type of Change:
**Delete irrelevant options.**

- Code
- User Interface

**Code/Quality Assurance Only**
- 16 px margin added 

### How Has This Been Tested?
margins
margins-1

### Checklist:
**Delete irrelevant options.**

- [*] My PR follows the style guidelines of this project
- [*] I have performed a self-review of my own code or materials
- [*] Any dependent changes have been merged 

**Code/Quality Assurance Only**
- [*] My changes generate no new warnings 
- [*] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by sakshi1499** [comment]
@yashshah2820 Why is there a formatting removed commit?

**Comment by yashshah2820** [comment]
Because the text got formatted when I was working on the files so I removed the formatting done by my editor :)

**Comment by sakshi1499** [comment]
Hmm, can you do squash the commits to 1 commit? I think the file changes are fine. I'll merge once you do this. @yashshah2820

**Comment by yashshah2820** [comment]
@sakshi1499 there are some changes which were required for a windows user like me to add in the settings, if I were to squash these commits then I would have to stage those changes as well but they are needed in this PR so consider the commits as it is I will squash the commits next time 😄

**Comment by anshumanv** [comment]
> Hmm, can you do squash the commits to 1 commit? I think the file changes are fine. I'll merge once you do this. @yashshah2820

Why not squash merge?

**Comment by sakshi1499** [comment]
@anshumanv We can squash merge, I find it a better practice though. Anyway since its difficult for him to squash. I'll merge the pr as is :)

**Pull request merged**
