### PR TITLE
Admin custom functionality like searching and filtering in news, resource and meetup

### LINKED ISSUE #347: Custom Admin Functionality
## Description
As a admin, I should be able to search and filter in admin page and use  the custom functionality for enhancing admin page. By default, it doesn't support search and filtering of the content in admin. So Admin can enhance the features of admin page and can have more control features.

## Mocks
It's an initial demo of the work.
screenshot from 2018-03-08 23-16-43

### Update [Required]
- [x] [Search by title, content etc ]
- [x] [Fiter by date like today, last seven days, months and year etc ]
- [x] [list_display extend of post ]

## Definition of Done
- [x] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
[10] hours

### PR DESCRIPTION
**Pull request by AnkurBegining**
### Description
Now Admin would able to use more functionality in his admin-page like searching, filtering and while he would type the title of news and meetup, slug would automatically fill up. 

Fixes #347 

### Type of Change:

**Code/Quality Assurance Only**
- New feature

### How Has This Been Tested?
Open admin and check for the above features for news, meetup and resources.

### Checklist:
**Delete irrelevant options.**

- [x] My PR follows the style guidelines of this project
- [x] I have performed a self-review of my own code or materials

**Code/Quality Assurance Only**
- [x] My changes generate no new warnings

### CODE REVIEW

**Comment by AnkurBegining** [comment]
@prachi1210 @tapasweni-pathak @sa7i Please review it.

**Comment by sakshi1499** [comment]
@AnkurBegining can you make the above changes and see if it still runs fine?

**Comment by sakshi1499** [comment]
@AnkurBegining Also, there are 5 commits can you squash them and just have one commit (provided you are working on it)?

**Comment by sammy1997** [comment]
@AnkurBegining Are you working on this? Or should we close it? @sakshi1499 @abhi20161997 We can wait for a couple of days and close this if the contributor doesn't respond

**Comment by sakshi1499** [comment]
@sammy1997  I think we can close this now.

**Comment by sakshi1499** [comment]
@sammy1997 Should I close it?

**Comment by sammy1997** [comment]
Closing this @sakshi1499 !

**Pull request closed without merging**
