### PR TITLE
updated systers logo link 373

### PR DESCRIPTION
**Pull request by manigedit**
### Description
I updated the systers logo broken link to the brand new logo.I am a total first timer. So, sorry for errors.

Fixes # [ISSUE]

### Type of Change:

- Code

**Code/Quality Assurance Only**
- Bug fix (non-breaking change which fixes an issue)

### How Has This Been Tested?
Describe the tests you ran to verify your changes. Provide instructions or GIFs so we can reproduce. List any relevant details for your test.

### Checklist:
**Delete irrelevant options.**

- [ ] My PR follows the style guidelines of this project
- [ ] I have performed a self-review of my own code or materials
- [ ] I have commented my code or provided relevant documentation, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] Any dependent changes have been merged 

**Code/Quality Assurance Only**
- [ ] My changes generate no new warnings 
- [ ] My PR currently breaks something (fix or feature that would cause existing functionality to not work as expected)
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been published in downstream modules

### CODE REVIEW

**Comment by sammy1997** [comment]
@manigedit can you link the issue in the PR description? Also, instead of adding an external logo link, I would suggest adding it to the image folder under sttic so that django can serve it and the URL wouldn't need to change

**Comment by manigedit** [comment]
@sammy1997  should I proceed to make the changes?

**Comment by sammy1997** [comment]
Yeah sure

**Comment by sammy1997** [comment]
@manigedit ? Any updates?

**Comment by sammy1997** [comment]
@sakshi1499 @abhi20161997 What should we do with this PR?

**Comment by sakshi1499** [comment]
@sammy1997 I think we can close this, what do you suggest?

**Comment by sammy1997** [comment]
Yeah please go ahead @sakshi1499 . You have access to the doc right? Please keep a record of the closed PRs in that doc. Thanks!

**Comment by sakshi1499** [comment]
@sammy1997 Yes Okay, have been adding there only. 

Closing this PR because there isn't any activity and the suggested changes haven't been implemented.

**Pull request closed without merging**
