### PR TITLE
Added the portal stream link to the readme

### LINKED ISSUE #482: Add section on README to redirect contributors to Zulip channel regarding portal
## Description

As a contributor,
I need to know where I can reach out the community,
so that I can discuss or see discussions of this project.

I would suggest adding a section such as "Contact us" or "How to reach us" to the README.
An example is what is on [mentorship-backend README](https://github.com/anitab-org/mentorship-backend/).

### Update [Required]
- [ ] Add contact section with AnitaB.org Open Source Zulip link and #portal stream link. 

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
1 hour

### PR DESCRIPTION
**Pull request by arunikayadav42**
### Description
Added a link that leads to the portal stream on the anita borg zulip organization.
Fixes #482

### CODE REVIEW

**Comment by sammy1997** [comment]
@arunikayadav42 Can you rebase your branch? There is an older commit by @mayburgos in your PR

**Comment by sammy1997** [comment]
@arunikayadav42 ? Can you make the update?

**Comment by arunikayadav42** [comment]
Sure! I have been a bit occupied due to the campus evacuation thing here. Will do it today.

**Comment by arunikayadav42** [comment]
> @arunikayadav42 ? Can you make the update?

how do I rebase it?

**Comment by sammy1997** [comment]
https://www.atlassian.com/git/tutorials/rewriting-history/git-rebase

@arunikayadav42

**Comment by sammy1997** [comment]
@arunikayadav42 I think you have made some mistake while rebasing! The PR is showing an older merge commit

**Comment by sammy1997** [comment]
@arunikayadav42 are you working on this?

**Comment by arunikayadav42** [comment]
@sammy1997 yes

**Comment by arunikayadav42** [comment]
> @arunikayadav42 are you working on this?

@sammy1997 done please review.

**Pull request merged**
