### PR TITLE
Added Image Field To Meetup

### LINKED ISSUE #453: Add image field to meetup
## Description
Users should be allowed to upload picture for their meetup inorder to improve the overall look and feel of the portal.

### Update [Required]
- [ ] Add image field to meetup form.
- [ ] Image should be displayed in upcoming meetup tab and meetup tab.

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
1 hours

### PR DESCRIPTION
**Pull request by ritwickraj78**
### Description
Added an image field to the meetup form and also image views to meetup and upcoming meetup pages. Fixed Bracket issue.
Screenshot from 2020-03-16 23-38-25

Fixes #453 and #479 

### Type of Change:
**Delete irrelevant options.**

- Code
- Quality Assurance
- User Interface

**Code/Quality Assurance Only**

- New feature (non-breaking change which adds functionality pre-approved by mentors)

### How Has This Been Tested?
All local tests as well as build tests have been done and tested.

### Checklist:
**Delete irrelevant options.**

- [x] My PR follows the style guidelines of this project
- [x] I have performed a self-review of my own code or materials
- [x] I have commented my code or provided relevant documentation, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] Any dependent changes have been merged 

**Code/Quality Assurance Only**
- [x] My changes generate no new warnings 
- [x] New and existing unit tests pass locally with my changes
Screenshot from 2020-03-16 22-18-10
Screenshot from 2020-03-16 22-17-24
Screenshot from 2020-03-16 22-12-56

### CODE REVIEW

**Comment by ritwickraj78** [comment]
@sammy1997  @abhi20161997  Could you please review this PR and merge it if it is fine.Thank you in advance.

**Comment by sammy1997** [comment]
Travis seems to be failing. Can you please check this?

**Comment by sammy1997** [comment]
@ritwickraj78 can you make separate PRs for separate issues?

**Comment by ritwickraj78** [comment]
@sammy1997 PR was failing because one of the test assertions were failing. Fixed it though. Shall I create a separate PR?

**Comment by sammy1997** [comment]
Can you unstage the migration files? You have pushed those as well

**Comment by ritwickraj78** [comment]
@sammy1997 So shall I undo the migrations?

**Comment by ritwickraj78** [comment]
@sammy1997 Tried to undo the migrations and amend the commit but build seems to fail. Could you help me out with this things?

**Comment by sammy1997** [comment]
Hmm...Strange! The Travis doesn't migrate the models it seems. The newly added field is missing from the migration which is causing the build to fail. I also saw that all the apps have their migration folders which should ideally have been in gitignore! Ok, do this...Add the migration files back. Also, pull the changes from the develop branch. Your local branches seem outdated!

**Comment by ritwickraj78** [comment]
@sammy1997  I shall do the required. Thanks for the help. I guess you can open another issue to make changes in the Travis.yml file to migrate the models. Thank you!

**Pull request closed without merging**
