### PR TITLE
add systers logo

### LINKED ISSUE #373: Systers logo is missing on Portal's GitHub Page
## Description
As a newcomer,
I need a proper Systers logo reference,
so that I can know which open source project falls under Systers.

### **Close Up**
screenshot from 2018-05-04 21-29-40

### **Full Screen**
screenshot from 2018-05-04 21-30-17

### Update [Required]
- [ ] Update the Systers logo to the [new branded logo](http://systers.io/images/systers-logo.png). 
- [ ] Fix the [broken png link](http://systers.org/systers-dev/lib/exe/fetch.php/systers-logo.png?w=300
) to properly reference an updated image.

### Enhancement to Update [Optional]
- [ ] Remove the old 2014 students, mentors, and project admins from the page. (A separate database is being created to properly assign contributors to the each repo's GitHub page.
- [ ] Look what has caused the logo to be missing and find a stable way (Amazon S3 storage?) to maintain images so they wouldn't fade away in the future. (Document first, then open a issue that helps solve this problem with the documentation attached.)

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
1 hours

### PR DESCRIPTION
**Pull request by Oishika-Pradhan**
### Description
This adds the logo to https://systers.io/portal/ and also updates the mentors and students.

Fixes #373 

### Type of Change:
- User Interface

**Code/Quality Assurance Only**
- Bug fix (non-breaking change which fixes an issue)

### How Has This Been Tested?
Screenshot provided below

screen shot 2018-05-22 at 11 32 21 am
screen shot 2018-05-22 at 11 31 43 am

### Checklist:
- [x] My PR follows the style guidelines of this project

**Code/Quality Assurance Only**
- [x] My changes generate no new warnings

### CODE REVIEW

**Comment by Oishika-Pradhan** [comment]
Can anyone look at this? @Fenn-CS @monajalal

**Comment by Fenn-CS** [comment]
@MeepyMay  @systers/maintainers-portal codacy reviews are blocked please take a look at this.

**Comment by Oishika-Pradhan** [comment]
@sa7i @monajalal I have updated the page with only the names of the students and mentors who have contributed to the portal. Please review.

**Comment by sammy1997** [comment]
@poojithansl @monajalal Any reviews on this? Should I review it?

**Comment by sakshi1499** [comment]
@sammy1997 They haven't replied. How do you want to proceed with this one?

**Comment by sammy1997** [comment]
@sakshi1499 The changes seem fine. The list might need to be updated, but that's a separate issue IG? Maybe you can review it and we can merge it?

**Comment by sakshi1499** [comment]
@sammy1997 I don't think we should merge it, the pull request is doing just two things and if one needs to be corrected by a separate issue, I don't think its worth merging. :( Should I close it then?

**Comment by sakshi1499** [comment]
Closing PR because of the following reasons, the list is not updated and the image hasn't been served properly. cc @sammy1997

**Pull request closed without merging**
