### PR TITLE
Added Meetup Location Membership to Profile Page, fixes #332

### LINKED ISSUE #332: Membership must also include Meetup Locations.
## Description
Membership of a user can be shown next to the user's profile. Currently, membership only includes the community membership. But, Meetup membership must also be included. 
e.g. If I am a Community Member of Systers and Meetup location member of London Systers. Membership only shows that I am part of Systers.

## Mocks
image

## Acceptance Criteria
Include Meetup Location membership and provide options to leave, leave as an organizer.
### Update [Required]
- [ ] Meet the acceptance criteria.

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
1/2 hours

### PR DESCRIPTION
**Pull request by Praful932**
### Description
Added Meetup Location Membership to Profile Page

Fixes #332  

### Type of Change:

- Code

**Code/Quality Assurance Only**
- Bug fix (non-breaking change which fixes an issue)

### How Has This Been Tested?
I have tested it locally.
main2
main1

test1
test2

### Checklist:

- [x] My PR follows the style guidelines of this project
- [x] I have performed a self-review of my own code or materials
- [x] I have commented my code or provided relevant documentation, particularly in hard-to-understand areas

**Code/Quality Assurance Only**
- [x] My changes generate no new warnings

### CODE REVIEW

**Comment by Praful932** [comment]
@sammy1997 I had trouble with rebase in the first PR. I have made a new PR. Please Check Thank you.

**Comment by sammy1997** [comment]
@Praful932 As you have added a new model and new views, you need to add some unit tests as well. Please do that and update the PR

**Comment by Praful932** [comment]
@sammy1997  Ok I'll add tests

**Comment by Praful932** [comment]
@sammy1997 I have added tests and updated the Pull Request. There are two test fails in `test_api_for_vms_post &  test_api_for_vms_get` when running whole View tests for meetup, Should a separate issue be created for that?

**Comment by Praful932** [comment]
> @Praful932 please don't create pull request directly to from your develop branch
@yashshah2820 How should I proceed?

**Comment by theyashshahs** [comment]
create a new branch, do the necessary changes and create a PR :)

**Comment by theyashshahs** [comment]
@Praful932 resolve the merge conflicts and change the PR title to follow the [commit styles](https://github.com/anitab-org/portal/wiki/Commit-Message-Style-Guide)

**Comment by Praful932** [comment]
> @Praful932 resolve the merge conflicts and change the PR title to follow the [commit styles](https://github.com/anitab-org/portal/wiki/Commit-Message-Style-Guide)

@yashshah2820 Should I do it in this PR, or close this and create a new one?

**Comment by theyashshahs** [comment]
do it in this PR :)

**Comment by theyashshahs** [comment]
ping @Praful932

**Comment by Praful932** [comment]
@yashshah2820 The Meetup Location Model is removed in [this](https://github.com/anitab-org/portal/commit/2d8c12fd625769b5266a5f349e096f2bca9efc4a) commit. So my changes have become obsolete. How should I proceed?

**Comment by sakshi1499** [comment]
@SanketDG I don't think we need this feature anymore. What do you suggest?

**Comment by sakshi1499** [comment]
Closing this PR as its not required anymore.

**Pull request closed without merging**
