### PR TITLE
Changes css, fix overlapping issue

### LINKED ISSUE #460: Messages overlapping with Headings/Text
## Description
As a Developer,
I need make some changes in the styling of the portal
so that the messages being displayed above the heading/text are easily readable.

## Mocks
overwriting issue
overwriting_issue2

### Update [Required]
- [x] Required changes in styling are made to ensure no overlapping.
### Enhancement to Update [Optional]
- [x] The messages are centre aligned so as to improve the overall feel. 

## Definition of Done
- [x] All of the required items are completed.
- [x] Approval by 1 mentor.

## Estimation
0.5 Hours

### PR DESCRIPTION
**Pull request by abhishekspeer**
### Description
Overlapping of messages with Heading/Text is fixed via changes in styling. 

Fixes #460 

### Type of Change:

- Code
- Quality Assurance
- User Interface

**Code/Quality Assurance Only**
- Bug fix (non-breaking change which fixes an issue)

### Mocks
screenshot from 2019-02-25 11-47-30
screenshot from 2019-02-25 11-46-25

### How Has This Been Tested?
Tested Locally

### Checklist:

- [x] My PR follows the style guidelines of this project
- [x] I have performed a self-review of my own code or materials

**Code/Quality Assurance Only**
- [x] My changes generate no new warnings 
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by abhishekspeer** [comment]
Thanks for reviewing. First of all, please check again, it’s not the views but the test_views. I had to make that changes because test cases were not dealed with previously, making it difficult for this PR to pass the Travis.

**Comment by aayush-05** [comment]
Which error were you facing in the builds : pagination error or assertion error ?

**Comment by abhishekspeer** [comment]
@aayush-05 please go through the test script once, you'll find the changes I've made there itself. Again, Thanks for reviewing!

**Comment by sammy1997** [comment]
Please resolve the merge conflict @abhishekspeer . Also, the current Travis build is passing, so I think you can remove the test file. Can you try that and see if the build passes?

**Comment by sammy1997** [comment]
That should resolve the merge conflict as well

**Comment by abhishekspeer** [comment]
Thanks for reviewing this PR @sammy1997. I'll make the required changes and and notify you once done. :)

**Comment by abhishekspeer** [comment]
@sammy1997 Could you please review it? Thanks a lot!

**Pull request merged**
