### PR TITLE
Fixes #467 and #482

### LINKED ISSUE #467: Links on Homepage redirects to 400 Bad Request page
## Description
As a user,
I need the links on the homepage to be correct,
so that I can learn more about AnitaB.org communities.

When clicking some buttons on the homepage, I get redirected to `400 Bad Request`, because old website - http://anitaborg.org/ - does not redirect to the current AnitaB official website - https://anitab.org/. 

E.g.: http://anitaborg.org/get-involved/systers/systers-initiatives/ should be http://anitab.org/get-involved/systers/systers-initiatives/ (which actually like this, redirects to https://anitab.org/systers/systers-initiatives/)

I think the file that handles this is [/develop/systers_portal/templates/common/index.html](https://github.com/systers/portal/blob/develop/systers_portal/templates/common/index.html).

## Mocks

What I get right now:
image

### Update [Required]
- [ ] Make all links on homepage redirect to a valid page instead of `400 Bad Request`

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
1 hour

### PR DESCRIPTION
**Pull request by sayashraaj**
### Description
Changed anitaborg.org to anitab.org
Added Contact Us section for Portal

Fixes # [467] & [482]

### Type of Change:

- Code
- Documentation

### How Has This Been Tested?
Tested on my fork

### Checklist:

- [x] My PR follows the style guidelines of this project
- [x] I have performed a self-review of my own code or materials
- [x] I have commented my code or provided relevant documentation, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] Any dependent changes have been merged 

**Code/Quality Assurance Only**
- [x] My changes generate no new warnings 
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by sammy1997** [comment]
@sayashraaj I can see 3 commits on this. Please rebase your branch to show the commit only for the relevant issue!

**Comment by sayashraaj** [comment]
Sure! But I do not know how to rebase if I have not created a local repository and only edited the files on GitHub in my browser

**Comment by sammy1997** [comment]
@sayashraaj You have to fetch all the branches locally. Then you have to use git to do the rebase and push it to GitHub. Also, for the future, don't use GitHub for code changes!

**Comment by sammy1997** [comment]
Any updates @sayashraaj ? Should I close this PR?

**Comment by sayashraaj** [comment]
Hey, I have some personal difficulties due to the ongoing worldwide situation, please give some time

**Comment by sayashraaj** [comment]
Hey, when I clone the forked repo in my local machine, it is fine, but when I add the "git remote add upstream https://github.com/sayashraaj/portal.git" command, it says "fatal: not a git repository (or any of the parent directories): .git"
Please help

**Comment by sammy1997** [comment]
Are you sure you are in the correct directory? After cloning did you do a cd?

**Comment by sayashraaj** [comment]
I have rebased and pushed

**Comment by sammy1997** [comment]
Firstly, there are some merge conflicts. Secondly, please send 1 PR for 1 issue instead of 1 PR for 2 issues

**Comment by sammy1997** [comment]
Closing this PR as I didn't get a response from the developer and there are multiple issues with the PR. cc @sakshi1499 @abhi20161997

**Pull request closed without merging**
