### PR TITLE
Added Image Field To Meetup 

### LINKED ISSUE #453: Add image field to meetup
## Description
Users should be allowed to upload picture for their meetup inorder to improve the overall look and feel of the portal.

### Update [Required]
- [ ] Add image field to meetup form.
- [ ] Image should be displayed in upcoming meetup tab and meetup tab.

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
1 hours

### PR DESCRIPTION
**Pull request by ritwickraj78**
### Description
Adding image to meetup page and to upcoming meetup page. 

Fixes #453  

### Type of Change:
**Delete irrelevant options.**

- Code
- Quality Assurance
- User Interface

**Code/Quality Assurance Only**
- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality pre-approved by mentors)

### How Has This Been Tested?
Ran all local tests and Travic CI build runs successfully

### Checklist:
**Delete irrelevant options.**

- [x] My PR follows the style guidelines of this project
- [x] I have performed a self-review of my own code or materials
- [x] Any dependent changes have been merged 

**Code/Quality Assurance Only**
- [x] My changes generate no new warnings 
- [x] New and existing unit tests pass locally with my changes

Screenshot from 2020-03-16 22-18-10
Screenshot from 2020-03-16 22-17-24

### CODE REVIEW

**Comment by ritwickraj78** [comment]
@sammy1997 I have closed the previous PR and opened a new PR with the necessary changes. Could you please have a look? Thank you

**Comment by sammy1997** [comment]
Can you separate the changes into 2 PRs solving 2 issues? Than 1 solving 2

**Comment by ritwickraj78** [comment]
Yaa sure. I'll do it.

**Comment by ritwickraj78** [comment]
@sammy1997 I have made the necessary changes. Could you please review it?

**Comment by abhi20161997** [comment]
@ritwickraj78 please merge the commits into one for better reference

**Pull request merged**
