### PR TITLE
Remove frontend glitches, Improve responsive css

### LINKED ISSUE #458: Remove design glitches at different screen sizes
## Description
As a developer,
I need to ensure that the portal has a layout free of glitches at all screen sizes while retaining the basic design of portal at the same time. This will accomplish a responsive design for every screen size and an experience tailored to handheld devices as well.

## Mocks
screenshot from 2018-12-22 19-49-29
screenshot from 2018-12-22 19-50-12
screenshot from 2018-12-22 19-50-23

### Update [Required]
- [x] CONTACT not shifting below from the lower navigation bar. 
- [x] SIGN UP and LOGIN does not overlap Systers Logo on reducing screen width.
- [x] Orientation of SIGN UP and LOGIN is fixed at reduced screen width. 

### Enhancement to Update [Optional]
- [x] Fix the signup and login button orientation on devices with smaller screen size.
- [x] Minimize the horizontal scrolling on handheld devices to offer a better user experience.

## Definition of Done
- [x] All of the required items are completed.
- [x] Approval by 1 mentor.

## Estimation
2 hours

### PR DESCRIPTION
**Pull request by abhishekspeer**
### Description
Earlier the portal lacked a responsive design and had a lot of glitches at different screen sizes including improper orientation of navbar items at different screen sizes, overlapping of sign in and sign up buttons with the Systers logo on reducing screen sizes and horizontal scrolling on handheld screens. These are resolved as illustrated below in the mocks.

Fixes #458 

### Mocks 
- CONTACT orientation fixed.
    - Current
contactp
contact2

   - Proposed
contact3
contact4

- SIGN UP and LOGIN does not overlap Systers Logo on reducing screen width.
    - Current
susi2

    - Proposed
susi4
susi5

- Orientation of SIGN UP and LOGIN is fixed at reduced screen width.
    - Current
l1

    - Proposed
l3

- No Horizontal exploring for screens on handheld devices.
    - Current
ippe
p2e

    - Proposed
ippf
p2f

- Other changes include replacement of current sign in and sign up buttons by buttons with rounded edges to match other buttons used in the portal.
 
### Type of Change:
- Code
- Quality Assurance
- User Interface

**Code/Quality Assurance Only**
- Bug fix (non-breaking change which fixes an issue)

### How Has This Been Tested?
NA

### Checklist:
- [x] My PR follows the style guidelines of this project
- [x] I have performed a self-review of my own code or materials

**Code/Quality Assurance Only**
- [x] My changes generate no new warnings 
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by abhishekspeer** [comment]
@abhi20161997 
I have made the required changes to fix issue #458. It fixes all the glitches and achieves a better user experience on devices with smaller screens.
Please review this PR and suggest changes, if you expect any. :)

**Comment by sammy1997** [comment]
@abhishekspeer Please squash the 2 commits into 1. That would be easier to review and is the recommended practice.

**Comment by abhishekspeer** [comment]
@sammy1997  Thank you so much for reviewing this Pull Request. As you have suggested, I've squashed the commits into a single one. Please have a look.

**Comment by abhi20161997** [comment]
@abhishekspeer LGTM. @yatna @sa7i Please can you too review this?

**Comment by sammy1997** [comment]
@abhishekspeer Please resolve the conflict here as well. Also, I see a lot of tabs as changes! Did you have to do this for Codacy? Or was this due to the editor?

**Comment by abhishekspeer** [comment]
Yes @sammy1997, that was due to codacy. I'll make the required changes and get back to you.

**Comment by abhishekspeer** [comment]
@sammy1997, Could you please review it now? Thanks!

**Comment by abhishekspeer** [comment]
Ping @sammy1997, Is there any change you expect me to make? I observed that you assigned the issue related to me yesterday. Please don't mind me tagging you again, was a bit confused. Thanks! :)

**Comment by sammy1997** [comment]
@abhishekspeer There's still some merge conflict. Can you resolve it and also, can you change the commit message to something more relevant to the issue than "Unstaged test_views"? I will merge it once these changes are done!

**Comment by abhishekspeer** [comment]
@sammy1997 Done.

**Comment by abhishekspeer** [comment]
@sammy1997 I guess you’ve missed this ticket. Could you please merge this now?

**Comment by abhi20161997** [comment]
@sammy1997  LGTM as well ! Merging

**Pull request merged**
