### PR TITLE
Update broken links in CONTRIBUTING.md

### LINKED ISSUE #494: Update references on CONTRIBUTING.md from slack to zulip
## Description

As a contributor,
I need updated references to communication channels used by the community,
so that I can reach out to the community in the correct channels.

Contributing guidelines has still a reference to Slack channels. It should have link to Zulip and the appropriate stream. This should minimize confusion from newcomers

### Update [Required]
- [ ] Update CONTRIBUTING.md to have links to Zulip space and stream instead of Slack channel.

## Definition of Done
- [ ] All of the required items are completed.
- [x] Approval by 1 mentor.

## Estimation

30 min

### PR DESCRIPTION
**Pull request by bismitaguha**
### Description
 Update CONTRIBUTING.md to have links to Zulip space and stream instead of Slack channel.

Fixes #494 

### Type of Change:
**Delete irrelevant options.**

- Documentation

### How Has This Been Tested?
No tests needed. Only a Documentation fix.
### Checklist:
**Delete irrelevant options.**

- [x] My PR follows the style guidelines of this project
- [x] I have made corresponding changes to the documentation

### CODE REVIEW

**Comment by bismitaguha** [comment]
@isabelcosta Please review this PR.

**Comment by bismitaguha** [comment]
@isabelcosta I have made the suggested changes. Please review.

**Comment by sammy1997** [comment]
@bismitaguha Please squash your commits. There are 2 commits in the PR! @isabelcosta Do you want any other changes?

**Comment by bismitaguha** [comment]
@sammy1997 @isabelcosta I have resolved the suggested changes. Please review.

**Comment by sammy1997** [comment]
Sorry for that change request. It happened by accident! I have approved this

**Pull request merged**
