### PR TITLE
Migrating to Bootstrap4

### LINKED ISSUE #449: Migrating from Bootstrap3 to Bootstrap4
## Description
As a developer,
I need to make sure that the bootstrap version is updated from bootstrap 3 to 4,
so that I can easily make changes in the files following the latest documentation.

## Mocks
N/A

### Update [Required]
- [ ] Bootstrap css and js files need to be updated.
## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
0.5 hours

### PR DESCRIPTION
**Pull request by ritwickraj78**
### Description
Migrated to Bootstrap 4 from Bootstrap 3.

Fixes #449 

### Type of Change:
**Delete irrelevant options.**

- Quality Assurance

**Code/Quality Assurance Only**
- New feature (non-breaking change which adds functionality pre-approved by mentors)

### How Has This Been Tested?
All local as well as CI tests pass. It has been made sure that nothing is broken while migrating.

### Checklist:
**Delete irrelevant options.**

- [x] My PR follows the style guidelines of this project
- [x] I have performed a self-review of my own code or materials

**Code/Quality Assurance Only**
- [x] My changes generate no new warnings 
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by sakshi1499** [comment]
@ritwickraj78 Have you tested it in your local system? 
image
The above image is from the documentation.
image
Can we implement this in styles.css as well?

**Comment by ritwickraj78** [comment]
@sakshi1499 Even I went through the documentation and it seems changing to bootstrap 4 would be quite a Herculean task. There have to be more changes than I expected. So shall I continue with it or leave it for now?

**Comment by sakshi1499** [comment]
@ritwickraj78 Yes I agree there will be many changes. @sammy1997 What do you suggest?

**Comment by sakshi1499** [comment]
@ritwickraj78 I would suggest you to go ahead and properly migrate to Bootstrap4. Take time, I understand that it will be a huge task.

**Comment by sammy1997** [comment]
@sakshi1499 @ritwickraj78 I think we should close this and make the issue available for the community

**Comment by sakshi1499** [comment]
@sammy1997 Yes. I second you on this. Closing this and making it available to the community. :)

**Pull request closed without merging**
